language: node_js
branches:
  only:
    - master
cache:
  apt: true
  directories:
    - node_modules
node_js:
  - '5'
  - '4'
before_install:
  - 'npm install -g npm@latest'
after_success:
  - npm run coveralls
